version: 2.1
orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test:ci
            - codecov/upload:
                token: 45d8de48-7877-4744-bfc6-3ec34862914e
                file: coverage/clover.xml
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn lint
  
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - lint
