version: 2.1
orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test:ci
            - codecov/upload:
                token: 9073e816-df3d-41aa-a501-ff2441847744
                file: coverage/clover.xml
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn lint
  
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - lint
